[2022-08-17 16:07:45,167] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: move_gcs_bar_crawl_data_to_bq_workflow.insert_query_job_bar_crawl scheduled__2022-08-16T00:00:00+00:00 [queued]>
[2022-08-17 16:07:45,179] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: move_gcs_bar_crawl_data_to_bq_workflow.insert_query_job_bar_crawl scheduled__2022-08-16T00:00:00+00:00 [queued]>
[2022-08-17 16:07:45,180] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 16:07:45,180] {taskinstance.py:1239} INFO - Starting attempt 2 of 3
[2022-08-17 16:07:45,181] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 16:07:45,195] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): insert_query_job_bar_crawl> on 2022-08-16 00:00:00+00:00
[2022-08-17 16:07:45,202] {standard_task_runner.py:52} INFO - Started process 3512 to run task
[2022-08-17 16:07:45,206] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'move_gcs_bar_crawl_data_to_bq_workflow', 'insert_query_job_bar_crawl', 'scheduled__2022-08-16T00:00:00+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq.py', '--cfg-path', '/tmp/tmp4w_vpwo9', '--error-file', '/tmp/tmprp1950ib']
[2022-08-17 16:07:45,208] {standard_task_runner.py:77} INFO - Job 178: Subtask insert_query_job_bar_crawl
[2022-08-17 16:07:45,282] {logging_mixin.py:109} INFO - Running <TaskInstance: move_gcs_bar_crawl_data_to_bq_workflow.insert_query_job_bar_crawl scheduled__2022-08-16T00:00:00+00:00 [running]> on host 68a051b485fc
[2022-08-17 16:07:45,397] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=move_gcs_bar_crawl_data_to_bq_workflow
AIRFLOW_CTX_TASK_ID=insert_query_job_bar_crawl
AIRFLOW_CTX_EXECUTION_DATE=2022-08-16T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-16T00:00:00+00:00
[2022-08-17 16:07:45,400] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-08-17 16:07:45,404] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-08-17 16:07:45,415] {bigquery.py:1637} INFO - Inserting job ***_move_gcs_bar_crawl_data_to_bq_workflow_insert_query_job_bar_crawl_2022_08_16T00_00_00_00_00_94588846e079472e6b9c4b6956071955
[2022-08-17 16:07:45,958] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Table wise-logic-354820:bar_crawl_data.nyc_bar_crawl_data_partitioned was not found in location US

(job ID: airflow_move_gcs_bar_crawl_data_to_bq_workflow_insert_query_job_bar_crawl_2022_08_16T00_00_00_00_00_94588846e079472e6b9c4b6956071955)

                           -----Query Job SQL Follows-----                           

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:    
   2:            CREATE OR REPLACE TABLE bar_crawl_data.nyc_bar_crawl_data_partitoned
   3:            PARTITION BY DATE(record_date) AS
   4:            SELECT * FROM bar_crawl_data.nyc_bar_crawl_data_partitioned;
   5:        
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-08-17 16:07:45,990] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=move_gcs_bar_crawl_data_to_bq_workflow, task_id=insert_query_job_bar_crawl, execution_date=20220816T000000, start_date=20220817T160745, end_date=20220817T160745
[2022-08-17 16:07:46,071] {standard_task_runner.py:92} ERROR - Failed to execute job 178 for task insert_query_job_bar_crawl
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Table wise-logic-354820:bar_crawl_data.nyc_bar_crawl_data_partitioned was not found in location US

(job ID: airflow_move_gcs_bar_crawl_data_to_bq_workflow_insert_query_job_bar_crawl_2022_08_16T00_00_00_00_00_94588846e079472e6b9c4b6956071955)

                           -----Query Job SQL Follows-----                           

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:    
   2:            CREATE OR REPLACE TABLE bar_crawl_data.nyc_bar_crawl_data_partitoned
   3:            PARTITION BY DATE(record_date) AS
   4:            SELECT * FROM bar_crawl_data.nyc_bar_crawl_data_partitioned;
   5:        
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-08-17 16:07:46,150] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-08-17 16:07:46,286] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
