[2022-08-23 03:23:48,321] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: h1b_lca_data.entry_task scheduled__2021-01-10T06:00:00+00:00 [queued]>
[2022-08-23 03:23:48,335] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: h1b_lca_data.entry_task scheduled__2021-01-10T06:00:00+00:00 [queued]>
[2022-08-23 03:23:48,336] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 03:23:48,337] {taskinstance.py:1239} INFO - Starting attempt 9 of 9
[2022-08-23 03:23:48,338] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 03:23:48,353] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): entry_task> on 2021-01-10 06:00:00+00:00
[2022-08-23 03:23:48,360] {standard_task_runner.py:52} INFO - Started process 995 to run task
[2022-08-23 03:23:48,364] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'h1b_lca_data', 'entry_task', 'scheduled__2021-01-10T06:00:00+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/upload_h1b_data_to_gcp.py', '--cfg-path', '/tmp/tmpckgyur8_', '--error-file', '/tmp/tmptycur515']
[2022-08-23 03:23:48,366] {standard_task_runner.py:77} INFO - Job 216: Subtask entry_task
[2022-08-23 03:23:48,445] {logging_mixin.py:109} INFO - Running <TaskInstance: h1b_lca_data.entry_task scheduled__2021-01-10T06:00:00+00:00 [running]> on host 0afddbd69de7
[2022-08-23 03:23:48,510] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-08-23 03:23:48,539] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=h1b_lca_data
AIRFLOW_CTX_TASK_ID=entry_task
AIRFLOW_CTX_EXECUTION_DATE=2021-01-10T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-10T06:00:00+00:00
[2022-08-23 03:23:48,541] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-23 03:23:48,543] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 2021{ execution_date.strftime('%m') }}.xlsx"]
[2022-08-23 03:23:48,557] {subprocess.py:85} INFO - Output:
[2022-08-23 03:23:48,560] {subprocess.py:89} INFO - bash: -c: line 0: syntax error near unexpected token `('
[2022-08-23 03:23:48,561] {subprocess.py:89} INFO - bash: -c: line 0: `echo 2021{ execution_date.strftime('%m') }}.xlsx'
[2022-08-23 03:23:48,563] {subprocess.py:93} INFO - Command exited with return code 1
[2022-08-23 03:23:48,581] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-08-23 03:23:48,754] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=h1b_lca_data, task_id=entry_task, execution_date=20210110T060000, start_date=20220823T032348, end_date=20220823T032348
[2022-08-23 03:23:48,772] {standard_task_runner.py:92} ERROR - Failed to execute job 216 for task entry_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-08-23 03:23:48,823] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-08-23 03:23:48,876] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
